### PR TITLE
Same compiler, Upgraded GUI (except download function)

### PR DESCRIPTION
**Pull request by d4n5h**

### CODE REVIEW

**Comment by Thecakeisgit** [comment]
Some problems, very useless commits *-*. I think you can save your gui, and refork the repo, then add your GUI and send a new pull request :D

**Comment by Thecakeisgit** [comment]
I'll add my download function :D

**Comment by d4n5h** [comment]
@Thecakeisgit 
1. Ok i'll do that.
2. What about mouse simulation? It's pretty useful..
3. What are those "same problems"?

**Comment by Thecakeisgit** [comment]
1. Ok cool ;D
2. You can add it, i'm okay
3. Useless commits xDDD I hate them :D

**Comment by Thecakeisgit** [comment]
@d4n5h

**Comment by d4n5h** [comment]
@Thecakeisgit 
 I started with a new fork but i didn't manage to finish it.
You can just add the GUI by yourself if you want.
Just don't use CDN like i did..

**Comment by Thecakeisgit** [comment]
Okay ^^ np man

**Comment by d4n5h** [comment]
@Thecakeisgit Oh, and add mouse control.. it's just two commands..

**Comment by Thecakeisgit** [comment]
Okay i'll do it, but i'll do all this tomorrow :D

**Comment by d4n5h** [comment]
@Thecakeisgit 
What do you say about rewriting the interpreter with this architecture?
https://gist.github.com/d4n5h/dfaf4f015591f3e640214f6c2d11e5b0
It's just a really basic example and i did few things wrong. but mapping commands through dynamic creation of function is better, it's a bit more modular so you can use the basic interpreter for all sorts of thing rather than just DuckyScript to Arduino code conversion.

**Comment by Thecakeisgit** [comment]
Ok @d4n5h i'll think about it :D

**Comment by d4n5h** [comment]
@Thecakeisgit 
What i mean is that instead of splitting the code to parse into lines and loop through it, you run a loop for all the known commands and replace with the dynamically created function...
I think it's a better approach...

**Comment by d4n5h** [comment]
@Thecakeisgit ??

**Comment by Thecakeisgit** [comment]
I prefer the old versin ;D

**Comment by Thecakeisgit** [comment]
Dont remove your gists ^^ I think i'll use both @d4n5h

**Comment by d4n5h** [comment]
@Thecakeisgit  I think that the second example i gave you is the better approach of them all...
The only issue that i didn't have a solution for is the console debugging...
Like if STRING is missing an argument (a string in this case) - throw a console.error.
I think that the dynamically-created-functions and .apply can solve it but i need to figure out how to pass the backreferences to the dynamically-created-funcitons or maybe reversing it so that the dynamically-created-functions arguments will be passed as regex backreferences...

**Comment by d4n5h** [comment]
@Thecakeisgit Here you go, i figured out how to add console debugging:
https://gist.github.com/d4n5h/a7aab969a58b2ee9a597756151c4cb29

**Comment by d4n5h** [comment]
@Thecakeisgit ?

**Comment by Thecakeisgit** [comment]
Hmm i really apreciate the first gist, i think this gist isn't modular and you can do regex with the first gist ^^ :D

**Comment by d4n5h** [comment]
@Thecakeisgit 
Look again, it's not finished but still:
https://gist.github.com/d4n5h/a7aab969a58b2ee9a597756151c4cb29
And now, how in the name of fuck this is less modular?
Please explain yourself...

**Comment by d4n5h** [comment]
@Thecakeisgit Where did you go?? I miss you and your dumb comments that made me laugh... please come back....

**Comment by Thecakeisgit** [comment]
x) I answered in your gist xDDD School is taking my time, so it's hard to have time to commit and program :/

**Comment by d4n5h** [comment]
Look again:
https://gist.github.com/d4n5h/a7aab969a58b2ee9a597756151c4cb29

**Comment by d4n5h** [comment]
@Thecakeisgit I'm posting it here as well:
What do you mean by saying "regex it's not my cup of tea" (lol - Regex is **not** my cup of tea)?
Regex is one of the most useful tools in almost any programming language.
If it's "Not your cup of tea" then you're a terrible programmer.
Just say - "I don't know how to use/write regular expressions".

Anyway, i suggest that you'll let me take this project under my wing and close your repository.
I'm clearly a better programmer then you and Plazmaz and i've got more time to work on it.

This is the worst thing on GitHub, people create projects with bad code, someone more capable will want to make it better but the original creator of the project will hang on to is code like it's the best thing since the invention of the wheel and will refuse to adopt better solutions. Too much political correctness and pride made cool projects go to shit or even stop altogether.

**Comment by Nurrl** [comment]
Hi @d4n5h, so many work has been done so far, where did you go(And you were right, I was very dumb, and, yes regex is wonderful :3)

**Comment by d4n5h** [comment]
Hi there, thanks for the update! I'm sorry but I'm too busy with work and other stuff. I moved to Bangkok i lived and working here now for about an year. If I'll have more time on the weekends I'll chime in and try to help. You weren't dumb but yeah, my regex class is awesome lol

**Comment by Nurrl** [comment]
@d4n5h Take a look on the code when you have the time, this is almost what you've done, but wiyhouy your code since I totally forgot this work :,)

**Comment by d4n5h** [comment]
@Nurrl It looks a lot better, but it still requires a lot of unnecessary arrays.
With my class you can use only one array for everything.
I'm not saying that my class is perfect. it's near perfection but there are a few things to be added.
Use it and make it better.
To be honest, it might be a overkill for this project but i already built it so you might as well use it since it's still, objectively, a better solution.
It's nice to see you still maintain this project and you've made it a lot better, the GUI is really nice.
Though i liked the embedded console i've added which you didn't incorporate.

**Comment by Plazmaz** [comment]
@d4n5h that may have been my fault. I'm not sure how much of this was based on my original project, but there was a lot of array grossness going on for sure. I wrote the original project in an hour or two quite a while ago, so my code was terrible. I think moving forward starting to use more regex is good, however it does have performance impacts.

**Comment by d4n5h** [comment]
@Plazmaz You're right. but you can't really load big projects on a ATmega32U4 chip so it's not a serious issue. anyway, you're gaining back a lot more flexibility by using regex and since i use only one array and one for-loop in my class i think it will preform very good.

**Comment by d4n5h** [comment]
This is what i wrote one year ago:
In your solution:

1. You create an array of lines and then a giant array of words. also 3 arrays for keys, commands and combo keys.
In order to find and match the right commands you loop through all the lines + words + commands + keys + combo keys.
2. You use cases, which totally limits the the possibility of using the interpreter for other parsing jobs.
3. You use a class but your code is not OOP at all. in your code there is no real reason for using a class.
4. You put all the debugging inside the class.

In my solution:

1. I use one array (the map of keys/commands/whatever you want) and loop through one array (that means - one for-loop being used for everything).
2. I use regex replace and .bind to pass the regex back-references/group to the map of closures (still just in the one loop).
3. I don't use Cases or If/else.
4. My class is totally OOP and you can use class functions/variables inside the closures by using "this","self" and "arguments".
5. You can add console errors/debugging straight in the closures, not in the class.
With Regex - searching stuff to replace works in the same notion as "querying". e.g., You have conditions (if,else,and,or), you have back-references and you can decide what is considered a back-reference (a-z,A-Z,0-9 etc...). This is a much more powerful and flexible approach for parsing data.
7. Performance wise - I think it will parse little-bit slower than the hard-coded interpreter.
It doesn't really matter because you gain back a lot more flexibility in using regex back-reference groups.

**Comment by Nurrl** [comment]
The problem of your solution is the 'multi-combo', in example: `CTRL ALT t` that can't be made without multiplicating lines of code. And you need one function for each key:
```js
[
  a: function(args) {
    return 'typeKey(\'a\');'
  }
  b: /* Same, etc.. */
]

**Comment by Nurrl** [comment]
Separated keys arrays are here for a reason: Theses keys aren't interpreted in the same way:
  * **Modifiers**: ALT, SHIFT
  * **Type-able keys without the TYPE command**: ENTER, SPACE
  * **Type-able keys only with TYPE or combos**: a, b, c

**Comment by d4n5h** [comment]
You can do this (Just an example):
var map = [
  [/CTRL ALT (.*)/g,function(self,str){
    // Get everything
    var all = this.getAll(arguments,self);
    // Get current line location/number
    var ln = all.lineNumber;
    console.dir(all);
    if(str != '' && str != undefined){
      // Code here
    } else {
      // console.error here
    }
  }],
];

**Comment by d4n5h** [comment]
@Nurrl Yeah, for typing keys you'll have to do some code repetition. But it's the same in your solution, which have a lot more repetition anyway...

**Comment by d4n5h** [comment]
@Nurrl The only real problem that i need to figure out how to solve is updating the input data from within the map...
lineNumber will reduce if you'll use this.removeLines() or this.update() but the input string won't change which is a bit weird...

**Comment by Nurrl** [comment]
@d4n5h Yeah playing with JS references x)
And you have more and more code repetition for all combinations:
  * CTRL a
  * CTRL a
  * CTRL a
  * CTRL a

**Comment by Nurrl** [comment]
And with every combination .-. (CMD a, CMD ALT a, SPACE TAB, etc, ever and ever)
Look at the code now, this is fully modular, the last thing we could implement is regex match, but it's worthless I think..

**Comment by d4n5h** [comment]
@Nurrl Not at all. 
I'll wait another year until you figure it out and say that you we're dumb again.
No worries, i can wait.
BTW This is what you've managed to do in one year lmfao
Thanks for the update anyway...

**Comment by Nurrl** [comment]
@Plazmaz Am I totally dumb ? :')

**Comment by Plazmaz** [comment]
@Nurrl haven't looked into it yet, but at a glance @d4n5h is being a real dick, regardless of if he's right ;)

**Comment by d4n5h** [comment]
@Nurrl Not totally.
@Plazmaz I can see why both of you get along so well.
Anyway, stop bothering me with this project.

**Comment by Nurrl** [comment]
Okay see you in a year so 😆 @d4n5h

**Pull request closed without merging**
